language: android
sudo: required
jdk: oraclejdk8
android:
  components:
  - tools
  - platform-tools
  - build-tools-25.0.2
  - android-25
  - extra
  - add-on
licenses:
 - android-sdk-preview-license-.+
 - android-sdk-license-.+
 - google-gdk-license-.+
script:
- "./gradlew clean build connectedCheck -PdisablePreDex --stacktrace"