language: android
sudo: required
jdk: oraclejdk7
before_cache:
 -rm -f $HOME/.gradle/caches/modules-2/modules-2.lock
 -rm -fr $HOME/.gradle/caches/*/plugin-resolution/
cache:
 directories:
 -$HOME/.gradle/caches/
 -$HOME/.gradle/wrapper/
android:
  components:
    - tools
    - platform-tools
    - build-tools-25.0.2
    - android-25
    - extra
    - add-on
licenses:
 - android-sdk-preview-license-.+
 - android-sdk-license-.+
 - google-gdk-license-.+
 script:
 - "./gradlew clean test assemble -PdisablePreDex --stacktrace --info"