language: android
sudo: required
jdk: oraclejdk8
android:
  components:
  - tools
  - platform-tools
  - build-tools-25.0.3
  - android-25
licenses:
 - android-sdk-license-.+
script:
- "./gradlew clean build assemble -PdisablePreDex --stacktrace"